job_list:
  - job_name: sec_company_tickers_list
    flag_dry_run: false
    user_agent: "Van Chau Dao vaanchaau@gmail.com"
    max_retries: 3
    raw_json_dir: files/sec-edgar/raw
    csv_dir: files/sec-edgar/tickers
  - job_name: annual_sec_10k_report
    flag_dry_run: false
    user_agent: "Van Chau Dao vaanchaau@gmail.com"
    companies:
      - AAPL
      - META
      - GOOGL
      - AMZN
      - NFLX
      - GS
    max_retries: 3
    tickers_csv_dir: files/sec-edgar/tickers
    pdf_dir: files/sec-edgar/10k-pdf
